debug: add logging to track down kma column error
Add console logs to fetchCityRecord to identify which exact query
is still using 'kma' instead of 'kma_code' column name

Error: column cities.kma does not exist - need to find source